version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=dataox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  parser:
    build: .
    command: python main.py
    env_file:
      - .env
    depends_on:
      - db